"""Geothermal feature engineering for LUMI.

Physics-based calculations for geothermal suitability and energy output.
Measured inputs: IHFC heat flow, GIS fault/volcano distances, NASA POWER temperature.
Estimated inputs: reservoir depth, flow rate, MW output (all flagged with assumptions).
"""

from __future__ import annotations

import json
import logging
import math
from pathlib import Path
from typing import Any

import pandas as pd

logger = logging.getLogger(__name__)

# Paths relative to this file -> project root -> datasets
_PROJECT_ROOT = Path(__file__).resolve().parents[4]
_DATASET_DIR = _PROJECT_ROOT / "GeothermalDatasets"
_LOCAL_DATA_DIR = Path(__file__).resolve().parent.parent / "local_data"

# Pre-extracted lookup files (generated by extract_kmz.py)
_FAULTS_JSON = _LOCAL_DATA_DIR / "geothermal_faults.json"
_VOLCANOES_JSON = _LOCAL_DATA_DIR / "geothermal_volcanoes.json"
_HEATFLOW_CSV = _LOCAL_DATA_DIR / "geothermal_heatflow.csv"

# Constants
CP_KJ_KG_C = 4.186  # kJ/kg C
BINARY_EFFICIENCY = 0.12
FLASH_EFFICIENCY = 0.15
DEFAULT_RESERVOIR_DEPTH_M = 2000.0
REINJECTION_TEMP_C = 70.0

# Philippine bounding box for filtering global datasets
PH_MIN_LAT, PH_MAX_LAT = 4.0, 21.5
PH_MIN_LON, PH_MAX_LON = 116.0, 127.0


def _haversine(lat1: float, lon1: float, lat2: float, lon2: float) -> float:
    """Return distance between two lat/lon points in kilometres."""
    R = 6371.0
    phi1, phi2 = math.radians(lat1), math.radians(lat2)
    dphi = math.radians(lat2 - lat1)
    dlambda = math.radians(lon2 - lon1)
    a = (
        math.sin(dphi / 2) ** 2
        + math.cos(phi1) * math.cos(phi2) * math.sin(dlambda / 2) ** 2
    )
    c = 2 * math.atan2(math.sqrt(a), math.sqrt(1 - a))
    return R * c


def _normalize(value: float | None, min_v: float, max_v: float) -> float:
    if value is None or max_v == min_v:
        return 0.0
    return max(0.0, min(1.0, (value - min_v) / (max_v - min_v)))


def load_geothermal_datasets() -> dict[str, Any]:
    """Load pre-extracted geothermal datasets into memory.

    Returns dict with keys: faults, volcanoes, heatflow, aquifers.
    """
    datasets: dict[str, Any] = {"faults": [], "volcanoes": [], "heatflow": None, "aquifers": None}

    if _FAULTS_JSON.exists():
        with open(_FAULTS_JSON, "r", encoding="utf-8") as f:
            datasets["faults"] = json.load(f)
    else:
        logger.warning("Fault data not found at %s", _FAULTS_JSON)

    if _VOLCANOES_JSON.exists():
        with open(_VOLCANOES_JSON, "r", encoding="utf-8") as f:
            datasets["volcanoes"] = json.load(f)
    else:
        logger.warning("Volcano data not found at %s", _VOLCANOES_JSON)

    if _HEATFLOW_CSV.exists():
        datasets["heatflow"] = pd.read_csv(_HEATFLOW_CSV)
    else:
        logger.warning("Heatflow data not found at %s", _HEATFLOW_CSV)

    aquifer_path = _DATASET_DIR / "aquifer_properties.csv"
    if aquifer_path.exists():
        datasets["aquifers"] = pd.read_csv(aquifer_path)
    else:
        logger.warning("Aquifer data not found at %s", aquifer_path)

    return datasets


def calculate_fault_distance(muni_lat: float, muni_lon: float, faults: list[dict] | None = None) -> float | None:
    """Return distance (km) from municipality to the nearest active fault.

    Args:
        muni_lat: Municipality latitude.
        muni_lon: Municipality longitude.
        faults: List of fault dicts with 'lat', 'lon', 'length_km'. Loaded
            automatically if not provided.

    Returns:
        Distance in kilometres, or None if no fault data is available.
    """
    if faults is None:
        if not _FAULTS_JSON.exists():
            return None
        with open(_FAULTS_JSON, "r", encoding="utf-8") as f:
            faults = json.load(f)

    if not faults:
        return None

    min_dist = float("inf")
    for fault in faults:
        dist = _haversine(muni_lat, muni_lon, fault["lat"], fault["lon"])
        if dist < min_dist:
            min_dist = dist
    return round(min_dist, 2)


def calculate_fault_density(fault_lengths_km: float, municipality_area_km2: float) -> float | None:
    """Return fault density = fault_length_km / municipality_area_km2.

    Returns None if area is zero or missing.
    """
    if not municipality_area_km2 or municipality_area_km2 <= 0:
        return None
    return round(fault_lengths_km / municipality_area_km2, 6)


def calculate_volcano_distance(muni_lat: float, muni_lon: float, volcanoes: list[dict] | None = None) -> float | None:
    """Return distance (km) from municipality to the nearest volcano.

    Args:
        muni_lat: Municipality latitude.
        muni_lon: Municipality longitude.
        volcanoes: List of volcano dicts with 'lat', 'lon', 'name'. Loaded
            automatically if not provided.

    Returns:
        Distance in kilometres, or None if no volcano data is available.
    """
    if volcanoes is None:
        if not _VOLCANOES_JSON.exists():
            return None
        with open(_VOLCANOES_JSON, "r", encoding="utf-8") as f:
            volcanoes = json.load(f)

    if not volcanoes:
        return None

    min_dist = float("inf")
    for vol in volcanoes:
        dist = _haversine(muni_lat, muni_lon, vol["lat"], vol["lon"])
        if dist < min_dist:
            min_dist = dist
    return round(min_dist, 2)


def calculate_heatflow_score(heat_flow_mw_m2: float | None) -> float | None:
    """Normalize heat flow (mW/m2) to a 0-1 score using 40-120 range.

    Args:
        heat_flow_mw_m2: Heat flow value in mW/m2.

    Returns:
        Normalized score (0-1), or None if input is missing.
    """
    if heat_flow_mw_m2 is None:
        return None
    return round(_normalize(heat_flow_mw_m2, 40.0, 120.0), 4)


def calculate_aquifer_score(
    permeability: float | None,
    porosity: float | None,
    thickness: float | None,
) -> float | None:
    """Compute a composite aquifer suitability score (0-1).

    Weights: permeability 0.5, porosity 0.3, thickness 0.2.
    Uses log-scaled permeability because aquifer_properties.csv stores
    it as log10(m2) (negative values common).

    Args:
        permeability: Permeability (log10 m2) from aquifer dataset.
        porosity: Porosity fraction (0-1).
        thickness: Aquifer thickness in metres.

    Returns:
        Composite score 0-1, or None if any input is missing.
    """
    if permeability is None or porosity is None or thickness is None:
        return None

    # Permeability in dataset is log10(m2); typical range -17 to -11
    perm_score = _normalize(permeability, -17.0, -11.0)
    poro_score = _normalize(porosity, 0.0, 0.35)
    thick_score = _normalize(thickness, 0.0, 2000.0)

    score = (0.5 * perm_score) + (0.3 * poro_score) + (0.2 * thick_score)
    return round(max(0.0, min(1.0, score)), 4)


def calculate_geothermal_gradient(
    heat_flow_mw_m2: float | None, thermal_conductivity_wm_k: float = 2.5
) -> float | None:
    """Estimate geothermal gradient (C/km) from heat flow.

    Formula: G = q / k  where q = heat flow (W/m2) and k = thermal conductivity.
    We convert mW/m2 -> W/m2 by dividing by 1000.

    Args:
        heat_flow_mw_m2: Heat flow in mW/m2.
        thermal_conductivity_wm_k: Thermal conductivity in W/(m*K). Default 2.5
            for typical crustal rock.

    Returns:
        Gradient in C/km, or None if input is missing.
    """
    if heat_flow_mw_m2 is None or thermal_conductivity_wm_k <= 0:
        return None
    q_wm2 = heat_flow_mw_m2 / 1000.0
    gradient_c_m = q_wm2 / thermal_conductivity_wm_k
    gradient_c_km = gradient_c_m * 1000.0
    return round(gradient_c_km, 3)


def calculate_reservoir_temperature(
    surface_temp_c: float | None,
    gradient_c_km: float | None,
    depth_m: float = DEFAULT_RESERVOIR_DEPTH_M,
) -> float | None:
    """Estimate reservoir temperature using Ts + (G * Depth).

    Args:
        surface_temp_c: NASA POWER average surface temperature (C).
        gradient_c_km: Geothermal gradient (C/km).
        depth_m: Estimated reservoir depth in metres. Default 2000 m.

    Returns:
        Reservoir temperature in C, or None if inputs are missing.
    """
    if surface_temp_c is None or gradient_c_km is None:
        return None
    depth_km = depth_m / 1000.0
    temp = surface_temp_c + (gradient_c_km * depth_km)
    return round(temp, 2)


def estimate_flow_rate(
    aquifer_score: float | None,
    permeability_log10_m2: float | None,
) -> float | None:
    """Estimate geothermal flow rate (kg/s) from aquifer properties.

    When direct flow data is unavailable, we infer a plausible flow
    from aquifer permeability and score. Based on literature ranges
    for small-to-medium geothermal fields (10-500 kg/s).

    Args:
        aquifer_score: Composite aquifer suitability (0-1).
        permeability_log10_m2: Log10 permeability (m2).

    Returns:
        Estimated flow rate in kg/s, or None if inputs are missing.
    """
    if aquifer_score is None or permeability_log10_m2 is None:
        return None

    # Base estimate scales with aquifer quality and permeability
    # Higher permeability (less negative log10) -> higher flow
    perm_factor = max(0.0, _normalize(permeability_log10_m2, -17.0, -11.0))
    flow = 10.0 + (aquifer_score * perm_factor * 400.0)
    return round(flow, 2)


def compute_geothermal_suitability(
    muni_lat: float,
    muni_lon: float,
    surface_temp_c: float | None,
    datasets: dict[str, Any] | None = None,
    municipality_area_km2: float = 50.0,
) -> dict[str, Any]:
    """Compute all geothermal suitability metrics for a municipality.

    Args:
        muni_lat: Municipality latitude.
        muni_lon: Municipality longitude.
        surface_temp_c: NASA POWER average surface temperature (C).
        datasets: Pre-loaded datasets dict from load_geothermal_datasets().
        municipality_area_km2: Municipality area in km2 (used for fault density).

    Returns:
        Dict with all suitability fields and an overall score + classification.
    """
    if datasets is None:
        datasets = load_geothermal_datasets()

    # Fault / volcano distances
    fault_dist = calculate_fault_distance(muni_lat, muni_lon, datasets.get("faults"))
    volcano_dist = calculate_volcano_distance(muni_lat, muni_lon, datasets.get("volcanoes"))

    # Heat flow (nearest point within reasonable distance)
    heat_flow_val: float | None = None
    heat_flow_score: float | None = None
    gradient: float | None = None
    hf_df = datasets.get("heatflow")
    if hf_df is not None and not hf_df.empty:
        # Find nearest heat-flow measurement
        min_hfd = float("inf")
        for _, row in hf_df.iterrows():
            d = _haversine(muni_lat, muni_lon, row["lat"], row["lon"])
            if d < min_hfd:
                min_hfd = d
                heat_flow_val = float(row.get("heat_flow_mw_m2", 0))
        heat_flow_score = calculate_heatflow_score(heat_flow_val)
        gradient = calculate_geothermal_gradient(heat_flow_val)

    # Aquifer (grid cell data has no lat/lon; filter by country and use median)
    aquifer_score: float | None = None
    perm_val: float | None = None
    poro_val: float | None = None
    thick_val: float | None = None
    aq_df = datasets.get("aquifers")
    if aq_df is not None and not aq_df.empty:
        # The aquifer CSV lacks lat/lon; filter by Country name.
        country_col = "Country"
        if country_col in aq_df.columns:
            ph_aq = aq_df[aq_df[country_col].astype(str).str.contains("Philippines", case=False, na=False)]
        else:
            ph_aq = aq_df  # fallback: use entire dataset

        if not ph_aq.empty:
            perm_val = float(ph_aq["Permeability"].median()) if "Permeability" in ph_aq.columns else None
            poro_val = float(ph_aq["Porosity"].median()) if "Porosity" in ph_aq.columns else None
            thick_val = float(ph_aq["Aquifer_thickness"].median()) if "Aquifer_thickness" in ph_aq.columns else None
            if perm_val is not None and poro_val is not None and thick_val is not None:
                aquifer_score = calculate_aquifer_score(perm_val, poro_val, thick_val)

    # Temperature score (normalize surface temp 20-35 C as proxy)
    temp_score = _normalize(surface_temp_c, 20.0, 35.0) if surface_temp_c is not None else None

    # Fault density (simplified: assume one fault segment near municipality)
    fault_density = calculate_fault_density(5.0, municipality_area_km2) if fault_dist is not None else None

    # Overall weighted geothermal score
    weights = {
        "heat_flow": 0.35,
        "fault": 0.20,
        "volcano": 0.15,
        "aquifer": 0.20,
        "temperature": 0.10,
    }
    scores = {
        "heat_flow": heat_flow_score or 0.0,
        "fault": (1.0 - _normalize(fault_dist or 0, 0, 100)) if fault_dist is not None else 0.0,
        "volcano": (1.0 - _normalize(volcano_dist or 0, 0, 100)) if volcano_dist is not None else 0.0,
        "aquifer": aquifer_score or 0.0,
        "temperature": temp_score or 0.0,
    }
    avail = {
        k: 1.0 if scores[k] > 0 or (k == "fault" and fault_dist is not None) or (k == "volcano" and volcano_dist is not None) else 0.0
        for k in scores
    }
    total_weight = sum(weights[k] * avail[k] for k in weights)
    if total_weight > 0:
        geothermal_score = sum(scores[k] * weights[k] * avail[k] for k in weights) / total_weight
    else:
        geothermal_score = 0.0

    # Classification
    if geothermal_score >= 0.80:
        classification = "High"
    elif geothermal_score >= 0.60:
        classification = "Good"
    elif geothermal_score >= 0.40:
        classification = "Moderate"
    else:
        classification = "Low"

    return {
        "heat_flow_score": round(heat_flow_score, 4) if heat_flow_score is not None else None,
        "fault_density": fault_density,
        "fault_distance_km": fault_dist,
        "volcano_distance_km": volcano_dist,
        "aquifer_score": round(aquifer_score, 4) if aquifer_score is not None else None,
        "temperature_score": round(temp_score, 4) if temp_score is not None else None,
        "geothermal_score": round(geothermal_score, 4),
        "classification": classification,
        "_heat_flow_mw_m2": heat_flow_val,
        "_gradient_c_km": gradient,
        "_perm_log10": perm_val,
        "_porosity": poro_val,
        "_thickness_m": thick_val,
    }


def compute_geothermal_output(
    surface_temp_c: float | None,
    gradient_c_km: float | None,
    aquifer_score: float | None,
    permeability_log10_m2: float | None,
    depth_m: float = DEFAULT_RESERVOIR_DEPTH_M,
    plant_type: str = "binary",
) -> dict[str, Any]:
    """Compute geothermal energy output for a municipality.

    Uses physics-based formulas:
        Q = m * Cp * delta_T   (thermal power)
        P = Q * efficiency     (electric power)

    Args:
        surface_temp_c: NASA POWER surface temperature (C).
        gradient_c_km: Geothermal gradient (C/km).
        aquifer_score: Composite aquifer score (0-1).
        permeability_log10_m2: Log10 permeability (m2).
        depth_m: Estimated reservoir depth (m). Default 2000.
        plant_type: "binary" (0.12 eff) or "flash" (0.15 eff).

    Returns:
        Dict with thermal_power_mw, electric_power_mw, annual_energy_gwh,
        confidence_score, source, and assumption.
    """
    # Fallback: Philippine average surface temp when climate data is unavailable
    used_fallback_temp = False
    if surface_temp_c is None and gradient_c_km is not None:
        surface_temp_c = 27.0  # Philippine tropical average (C)
        used_fallback_temp = True

    reservoir_temp = calculate_reservoir_temperature(surface_temp_c, gradient_c_km, depth_m)
    flow_rate = estimate_flow_rate(aquifer_score, permeability_log10_m2)

    if reservoir_temp is None or flow_rate is None:
        return {
            "reservoir_temperature_c": None,
            "estimated_flow_rate_kg_s": None,
            "thermal_power_mw": None,
            "electric_power_mw": None,
            "annual_energy_gwh": None,
            "confidence_score": 0.0,
            "source": "Insufficient data",
            "assumption": "Missing measured heat flow or aquifer data for output estimation.",
        }

    delta_t = reservoir_temp - REINJECTION_TEMP_C
    if delta_t <= 0:
        delta_t = 1.0  # prevent zero/negative thermal power

    # Thermal power: Q = m_dot * Cp * delta_T  (Cp in kJ/kgC, convert to MW)
    # m_dot [kg/s] * Cp [kJ/kgC] * delta_T [C] = kJ/s = kW -> divide by 1000 for MW
    thermal_power_mw = (flow_rate * CP_KJ_KG_C * delta_t) / 1000.0

    efficiency = FLASH_EFFICIENCY if plant_type == "flash" else BINARY_EFFICIENCY
    electric_power_mw = thermal_power_mw * efficiency

    # Annual energy: MW * 8760 hours / 1000 = GWh
    annual_energy_gwh = (electric_power_mw * 8760.0) / 1000.0

    # Confidence based on data availability
    avail_heat = 1.0 if gradient_c_km is not None else 0.0
    avail_aq = 1.0 if aquifer_score is not None else 0.0
    avail_temp = 0.5 if used_fallback_temp else 1.0  # lower confidence if fallback
    confidence = (0.5 * avail_heat) + (0.3 * avail_aq) + (0.2 * avail_temp)
    confidence = round(min(1.0, confidence), 3)

    temp_note = "NASA POWER temperature (measured)" if not used_fallback_temp else "NASA POWER temperature unavailable; used Philippine average 27 C fallback"

    return {
        "reservoir_temperature_c": round(reservoir_temp, 2),
        "estimated_flow_rate_kg_s": round(flow_rate, 2),
        "thermal_power_mw": round(thermal_power_mw, 3),
        "electric_power_mw": round(electric_power_mw, 3),
        "annual_energy_gwh": round(annual_energy_gwh, 3),
        "confidence_score": confidence,
        "source": f"IHFC heat flow (measured), Zenodo aquifer properties (measured), {temp_note}.",
        "assumption": (
            f"Reservoir depth assumed {depth_m} m; "
            f"reinjection temperature {REINJECTION_TEMP_C} C; "
            f"plant type '{plant_type}' with efficiency {efficiency}. "
            f"Flow rate inferred from aquifer permeability when direct measurement unavailable."
        ),
    }
