import json
import os
from pathlib import Path
from typing import Any

import pandas as pd
import numpy as np


def _sanitize_nan(obj: Any) -> Any:
    """Recursively replace NaN / Inf floats with None for JSON safety."""
    if isinstance(obj, dict):
        return {k: _sanitize_nan(v) for k, v in obj.items()}
    if isinstance(obj, list):
        return [_sanitize_nan(v) for v in obj]
    if isinstance(obj, float) and (np.isnan(obj) or np.isinf(obj)):
        return None
    return obj


# DOE data is national-level only (2003-2024).
# Pre-computed forecasts exist as CSVs generated by DOE_arima_forecasting.ipynb.
# The production ML layer loads these pre-computed artifacts on startup
# and serves them without retraining on every request.

_DATA_DIR = Path(__file__).resolve().parents[3] / "DOE_Data_Extracted"
_GEOJSON_DIR = Path(__file__).resolve().parents[3] / "philippine_geojson"

# --- Loaders ---


def _load_csv(filename: str, subdir: str = "") -> pd.DataFrame | None:
    path = _DATA_DIR / subdir / filename if subdir else _DATA_DIR / filename
    if not path.exists():
        return None
    return pd.read_csv(path)


class EnergyHubML:
    """Lightweight ML prediction service for LUMI EnergyHub.

    Loads pre-computed ARIMA forecasts and historical data from the
    DOE_Data_Extracted directory.  Prefers data_v2_preprocessed/ over
    legacy data_v1/. No model retraining occurs at runtime.
    """

    def __init__(self) -> None:
        self._historical: pd.DataFrame | None = None
        self._forecast_consumption: pd.DataFrame | None = None
        self._forecast_peak: pd.DataFrame | None = None
        self._model_comparison: pd.DataFrame | None = None
        self._tabula_raw: pd.DataFrame | None = None
        self._provincial_consumption: pd.DataFrame | None = None
        self._regional_sales: pd.DataFrame | None = None
        self._irena_capacity: pd.DataFrame | None = None
        self._irena_generation: pd.DataFrame | None = None
        self._irena_renewable_share: pd.DataFrame | None = None
        self._meralco_rates: pd.DataFrame | None = None
        self._solar_atlas: pd.DataFrame | None = None
        self._load_all()

    def _load_all(self) -> None:
        # Prefer v2 preprocessed; fall back to v1 for backward compatibility
        def _prefer_v2(filename: str) -> pd.DataFrame | None:
            v2 = _load_csv(filename, "data_v2_preprocessed")
            return v2 if v2 is not None else _load_csv(filename, "data_v1")

        self._historical = _prefer_v2("master_preprocessed.csv")
        self._forecast_consumption = _prefer_v2("forecast_consumption_2025_2030.csv")
        self._forecast_peak = _prefer_v2("forecast_peak_demand_2025_2030.csv")
        self._model_comparison = _prefer_v2("model_comparison_results.csv")
        self._tabula_raw = _load_csv("Tabula_DOE_Data.csv", "data_v1")
        self._provincial_consumption = _load_csv("provincial_consumption_2003_2025.csv", "data_v2_preprocessed")
        self._regional_sales = _load_csv("regional_sales_2025.csv", "data_v2_preprocessed")
        self._irena_capacity = _load_csv("irena_ph_capacity_by_tech.csv", "data_v2_preprocessed")
        self._irena_generation = _load_csv("irena_ph_generation_by_tech.csv", "data_v2_preprocessed")
        self._irena_renewable_share = _load_csv("irena_renewable_share.csv", "data_v2_preprocessed")
        self._meralco_rates = _load_csv("meralco_rates_2011_2020.csv", "data_v2_preprocessed")
        self._solar_atlas = _load_csv("solar_atlas_ph.csv", "data_v2_preprocessed")

    # --- Public API ---

    def get_latest_statistics(self) -> dict[str, Any]:
        """Return the most recent year’s national energy snapshot."""
        if self._historical is None or self._historical.empty:
            return {}
        df = self._historical
        latest = df.iloc[-1]
        latest_year = int(latest["year"])

        total_consumption = float(latest.get("total_consumption_gwh", 0))
        total_peak = float(latest.get("total_peak_demand_mw", 0))
        total_generation = float(latest.get("total_generation_gwh", 0))
        renewable_gen = float(latest.get("renewable_generation_gwh", 0))
        renewable_share = (renewable_gen / total_consumption * 100) if total_consumption else 0.0

        return _sanitize_nan({
            "year": latest_year,
            "total_consumption_gwh": round(total_consumption, 2),
            "total_peak_demand_mw": round(total_peak, 2),
            "total_generation_gwh": round(total_generation, 2),
            "renewable_generation_gwh": round(renewable_gen, 2),
            "renewable_share_pct": round(renewable_share, 2),
            "capacity_margin_mw": round(float(latest.get("capacity_margin_mw", 0)), 2),
            "capacity_margin_pct": round(float(latest.get("capacity_margin_pct", 0)), 2),
        })

    def get_historical_trends(self) -> dict[str, Any]:
        """Return year-by-year national trends for charting."""
        if self._historical is None or self._historical.empty:
            return {"years": [], "series": {}}
        df = self._historical.sort_values("year")
        years = df["year"].astype(int).tolist()

        series = {
            "total_consumption_gwh": df["total_consumption_gwh"].round(2).tolist(),
            "total_peak_demand_mw": df["total_peak_demand_mw"].round(2).tolist(),
            "total_generation_gwh": df.get("total_generation_gwh", pd.Series([], dtype=float)).round(2).tolist(),
            "renewable_generation_gwh": df["renewable_generation_gwh"].round(2).tolist(),
            "renewable_share_pct": df.get("renewable_share_pct", pd.Series([], dtype=float)).round(2).tolist(),
            "coal_generation_gwh": df.get("coal_generation_gwh", pd.Series([], dtype=float)).round(2).tolist(),
            "natural_gas_generation_gwh": df.get("natural_gas_generation_gwh", pd.Series([], dtype=float)).round(2).tolist(),
            "oil_based_generation_gwh": df.get("oil_based_generation_gwh", pd.Series([], dtype=float)).round(2).tolist(),
            "hydro_generation_gwh": df.get("hydro_generation_gwh", pd.Series([], dtype=float)).round(2).tolist(),
            "geothermal_generation_gwh": df.get("geothermal_generation_gwh", pd.Series([], dtype=float)).round(2).tolist(),
            "solar_generation_gwh": df.get("solar_generation_gwh", pd.Series([], dtype=float)).round(2).tolist(),
            "wind_generation_gwh": df.get("wind_generation_gwh", pd.Series([], dtype=float)).round(2).tolist(),
        }
        return _sanitize_nan({"years": years, "series": series})

    def get_forecast(self, metric: str = "consumption") -> dict[str, Any]:
        """Return the 2025-2030 ML forecast with confidence intervals."""
        if metric == "peak_demand":
            df = self._forecast_peak
            target_col = "total_peak_demand_mw"
        else:
            df = self._forecast_consumption
            target_col = "total_consumption_gwh"

        if df is None or df.empty:
            return {"forecast_years": [], "forecast_values": [], "ci_lower": [], "ci_upper": []}

        years = df["year"].astype(int).tolist()
        values = df[target_col].round(2).tolist()
        ci_lower = df.get("ci_lower", pd.Series([None] * len(df))).round(2).tolist()
        ci_upper = df.get("ci_upper", pd.Series([None] * len(df))).round(2).tolist()

        return _sanitize_nan({
            "forecast_years": years,
            "forecast_values": values,
            "ci_lower": ci_lower,
            "ci_upper": ci_upper,
            "model": "ARIMA(1,1,1)",
            "training_period": "2003-2020",
            "test_period": "2021-2024",
        })

    def get_model_comparison(self) -> list[dict[str, Any]]:
        """Return test-set performance across all trained models."""
        if self._model_comparison is None or self._model_comparison.empty:
            return []
        df = self._model_comparison.copy()
        df["mae"] = df["mae"].round(2)
        df["rmse"] = df["rmse"].round(2)
        df["mape"] = df["mape"].round(2)
        return _sanitize_nan(df.to_dict(orient="records"))

    def get_source_breakdown(self, year: int | None = None) -> dict[str, Any]:
        """Return generation by plant type for a given year (latest if None)."""
        if self._historical is None or self._historical.empty:
            return {}
        df = self._historical
        if year is None:
            row = df.iloc[-1]
            year = int(row["year"])
        else:
            match = df[df["year"] == year]
            if match.empty:
                return {}
            row = match.iloc[0]

        sources = {
            "coal": float(row.get("coal_generation_gwh", 0)),
            "natural_gas": float(row.get("natural_gas_generation_gwh", 0)),
            "oil_based": float(row.get("oil_based_generation_gwh", 0)),
            "geothermal": float(row.get("geothermal_generation_gwh", 0)),
            "hydro": float(row.get("hydro_generation_gwh", 0)),
            "solar": float(row.get("solar_generation_gwh", 0)),
            "wind": float(row.get("wind_generation_gwh", 0)),
            "biomass": float(row.get("biomass_generation_gwh", 0)),
        }
        total = sum(sources.values())
        shares = {k: round((v / total * 100), 2) if total else 0 for k, v in sources.items()}
        return _sanitize_nan({
            "year": year,
            "total_generation_gwh": round(total, 2),
            "generation_gwh": {k: round(v, 2) for k, v in sources.items()},
            "share_pct": shares,
        })

    def get_grid_breakdown(self, year: int | None = None) -> dict[str, Any]:
        """Return generation by grid (Luzon, Visayas, Mindanao)."""
        if self._historical is None or self._historical.empty:
            return {}
        df = self._historical
        if year is None:
            row = df.iloc[-1]
            year = int(row["year"])
        else:
            match = df[df["year"] == year]
            if match.empty:
                return {}
            row = match.iloc[0]

        grids = {
            "luzon": float(row.get("luzon_generation_gwh", 0)),
            "visayas": float(row.get("visayas_generation_gwh", 0)),
            "mindanao": float(row.get("mindanao_generation_gwh", 0)),
        }
        total = sum(grids.values())
        shares = {k: round((v / total * 100), 2) if total else 0 for k, v in grids.items()}
        return _sanitize_nan({
            "year": year,
            "total_generation_gwh": round(total, 2),
            "generation_gwh": {k: round(v, 2) for k, v in grids.items()},
            "share_pct": shares,
        })

    def get_ai_insight(self) -> dict[str, str]:
        """Generate a static AI-style insight based on the latest data.

        In a production system this would call an LLM; here we return
        pre-computed, data-backed observations to avoid latency and
        cost while still providing useful narrative context.
        """
        if self._historical is None or self._historical.empty:
            return {"insight": "No data available.", "recommendation": ""}

        df = self._historical.sort_values("year")
        latest = df.iloc[-1]
        prev = df.iloc[-2] if len(df) > 1 else latest
        latest_year = int(latest["year"])

        consumption = float(latest["total_consumption_gwh"])
        prev_consumption = float(prev["total_consumption_gwh"])
        growth = ((consumption / prev_consumption) - 1) * 100 if prev_consumption else 0

        renewable_share = float(latest.get("renewable_share_pct", 0))
        capacity_margin = float(latest.get("capacity_margin_pct", 0))

        insight = (
            f"In {latest_year}, Philippine total electricity consumption reached "
            f"{consumption:,.0f} GWh, marking a {growth:.1f}% year-over-year change. "
            f"Renewable energy accounted for {renewable_share:.1f}% of the national mix. "
        )

        if capacity_margin < 30:
            insight += (
                f"The capacity margin stands at {capacity_margin:.1f}%, indicating "
                f"elevated grid stress. Infrastructure expansion should be prioritized."
            )
            recommendation = (
                "Consider accelerating renewable projects and demand-side management "
                "programs to relieve peak-period strain."
            )
        else:
            insight += (
                f"The capacity margin of {capacity_margin:.1f}% provides adequate "
                f"headroom for demand growth in the near term."
            )
            recommendation = (
                "Continue diversifying the generation mix with cost-effective renewables "
                "to maintain long-term supply security."
            )

        # Add forecast-based insight if available
        forecast = self.get_forecast("consumption")
        if forecast.get("forecast_values"):
            f_2030 = forecast["forecast_values"][-1]
            f_growth = ((f_2030 / consumption) - 1) * 100
            insight += (
                f" The ARIMA(1,1,1) model projects consumption will reach "
                f"{f_2030:,.0f} GWh by 2030, a cumulative growth of {f_growth:.1f}% "
                f"from {latest_year}."
            )

        return _sanitize_nan({
            "insight": insight,
            "recommendation": recommendation,
            "data_year": latest_year,
        })

    # --- Provincial / Regional Demand ---

    def get_provincial_consumption(self, region: str | None = None) -> dict[str, Any]:
        """Return provincial/regional consumption breakdown from DOE Annex 8.

        Values are in MWh as reported by DOE.  If region is None, all
        regions are returned.
        """
        if self._provincial_consumption is None or self._provincial_consumption.empty:
            return {"items": []}
        df = self._provincial_consumption.copy()
        if region:
            df = df[df["region"].str.upper() == region.upper()]
        items = df.to_dict(orient="records")
        return _sanitize_nan({"items": items})

    def get_regional_sales(self, region: str | None = None) -> dict[str, Any]:
        """Return 2025 total sales per region."""
        if self._regional_sales is None or self._regional_sales.empty:
            return {"items": []}
        df = self._regional_sales.copy()
        if region:
            df = df[df["region"].str.upper() == region.upper()]
        items = df.to_dict(orient="records")
        return _sanitize_nan({"items": items})

    # --- IRENA Benchmarking ---

    def get_irena_capacity(self, year: int | None = None) -> dict[str, Any]:
        """Return IRENA Philippines capacity by technology."""
        if self._irena_capacity is None or self._irena_capacity.empty:
            return {"items": []}
        df = self._irena_capacity.copy()
        if year:
            df = df[df["year"] == year]
        df["capacity_mw"] = df["capacity_mw"].round(2)
        items = df.to_dict(orient="records")
        return _sanitize_nan({"items": items})

    def get_irena_generation(self, year: int | None = None) -> dict[str, Any]:
        """Return IRENA Philippines generation by technology."""
        if self._irena_generation is None or self._irena_generation.empty:
            return {"items": []}
        df = self._irena_generation.copy()
        if year:
            df = df[df["year"] == year]
        df["generation_gwh"] = df["generation_gwh"].round(2)
        items = df.to_dict(orient="records")
        return _sanitize_nan({"items": items})

    def get_irena_renewable_share(self) -> dict[str, Any]:
        """Return year-by-year renewable share of electricity generation (%)."""
        if self._irena_renewable_share is None or self._irena_renewable_share.empty:
            return {"items": []}
        df = self._irena_renewable_share.copy()
        df["renewable_share_pct"] = df["renewable_share_pct"].round(2)
        items = df.to_dict(orient="records")
        return _sanitize_nan({"items": items})

    def get_meralco_rate(self, year: int | None = None) -> dict[str, Any]:
        """Return Meralco residential generation charge rate for a given year.

        If year is None, returns the most recent available year.
        """
        if self._meralco_rates is None or self._meralco_rates.empty:
            return {"rate_php_per_kwh": None, "year": None, "note": "Meralco data not available"}
        df = self._meralco_rates.copy()
        if year:
            match = df[df["year"] == year]
            if match.empty:
                return {"rate_php_per_kwh": None, "year": year, "note": "No data for requested year"}
            row = match.iloc[0]
        else:
            df = df.sort_values("year", ascending=True)
            row = df.iloc[-1]
        return _sanitize_nan({
            "rate_php_per_kwh": float(row["rate_php_per_kwh"]),
            "year": int(row["year"]),
            "customer_class": str(row.get("customer_class", "Residential")),
            "charge_component": str(row.get("charge_component", "Generation Energy Charge")),
            "note": "Meralco generation charge component only. Total bill includes transmission, distribution, and other charges.",
        })

    def get_solar_atlas(self, location: str | None = None) -> dict[str, Any]:
        """Return Global Solar Atlas data for Philippine locations.

        If location is provided, returns the closest match. Otherwise
        returns all sampled locations.
        """
        if self._solar_atlas is None or self._solar_atlas.empty:
            return {"items": [], "note": "Solar Atlas data not available"}
        df = self._solar_atlas.copy()
        if location:
            df = df[df["location"].str.lower().str.contains(location.lower(), regex=False)]
        items = df.to_dict(orient="records")
        return _sanitize_nan({"items": items, "note": "Data from Global Solar Atlas v2 (long-term annual averages)."})


# Singleton instance
_energyhub_ml: EnergyHubML | None = None


def get_energyhub_ml() -> EnergyHubML:
    global _energyhub_ml
    if _energyhub_ml is None:
        _energyhub_ml = EnergyHubML()
    return _energyhub_ml
